server:
  port: 6080

spring:
  application:
    name: short-link-service

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.5.53:8848
        username: nacos
        password: nacos

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/joker?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
    username: root
    password: root

  data:
    redis:
      host: 172.26.64.240
      port: 6379
      password: 123456
      database: 6
      jedis:
        pool:
          max-active: 8

logging:
  level:
    root: DEBUG

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

app:
  workId: 1
  workerIdBits: 10
